# =====================================================================
# common.mk - shared build rules for every example in examples/.
#
# An example's Makefile sets EXAMPLE (its binary name), then includes
# this file. Everything else (SDK paths, warnings, rpath, the shared
# common/ modules) is inherited, so samples stay short and consistent.
#
# Expects to be included from examples/<name>/Makefile, i.e. two levels
# below the repository root.
# =====================================================================

# --- Repository root (two levels up from the including Makefile) -----
ROOT     := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))

# --- Toolchain -------------------------------------------------------
CC       ?= gcc

# --- Architecture-matched VITURE SDK ---------------------------------
# Selects the arm64 SDK automatically on aarch64 hosts.
UNAME_M  := $(shell uname -m)
ifeq ($(UNAME_M),aarch64)
  SDK_DIR := $(ROOT)/sdk/viture_arm64
  SDK_LIB := $(SDK_DIR)/aarch64
else
  SDK_DIR := $(ROOT)/sdk/viture_x86_64
  SDK_LIB := $(SDK_DIR)/x86_64
endif
SDK_INC  := $(SDK_DIR)/include

# --- Shared modules (device scan, USB detach) ------------------------
COMMON_INC := $(ROOT)/common/include
COMMON_SRC := $(wildcard $(ROOT)/common/src/*.c)

# --- Layout of an individual example ---------------------------------
SRC_DIR  := src/source
INC_DIR  := src/headers
OBJ_DIR  := build
BIN_DIR  := bin
TARGET   := $(BIN_DIR)/$(EXAMPLE)

SRCS     := $(wildcard $(SRC_DIR)/*.c)

# Objects for this example's own sources plus the shared common ones.
OBJS     := $(patsubst $(SRC_DIR)/%.c,$(OBJ_DIR)/%.o,$(SRCS)) \
            $(patsubst $(ROOT)/common/src/%.c,$(OBJ_DIR)/common_%.o,$(COMMON_SRC))

# Examples may add pre-built objects, e.g. code generated by
# wayland-scanner. Set EXTRA_OBJS before including this file.
OBJS     += $(EXTRA_OBJS)

# --- Flags -----------------------------------------------------------
# C11 + POSIX.1-2008 for nanosleep/strtol/ioctl etc.
CFLAGS   ?= -std=c11 -D_POSIX_C_SOURCE=200809L \
            -Wall -Wextra -Wpedantic -Werror
CFLAGS   += -I$(INC_DIR) -I$(COMMON_INC) -I$(SDK_INC) -I$(OBJ_DIR) \
            $(EXTRA_CFLAGS)

# --disable-new-dtags emits DT_RPATH (not DT_RUNPATH) so the rpath also
# resolves the SDK's *transitive* deps (libcarina_vio -> OpenCV .so's),
# which DT_RUNPATH would not do.
LDFLAGS  += -L$(SDK_LIB) \
            -Wl,--disable-new-dtags \
            -Wl,-rpath,$(SDK_LIB) \
            -Wl,-rpath-link,$(SDK_LIB)
# Every example links all of common/, and xr_math.c uses tanf/sqrtf, so
# libm is a base dependency rather than a per-example one.
LDLIBS   += -lglasses -lpthread -lm $(EXTRA_LDLIBS)

# Belt-and-braces companion to the rpath: guarantees the SDK's deepest
# transitive deps resolve on any Linux loader.
RUN_ENV  := LD_LIBRARY_PATH="$(SDK_LIB):$$LD_LIBRARY_PATH"

# --- Rules -----------------------------------------------------------
.PHONY: all run clean dirs

all: $(TARGET)

$(TARGET): $(OBJS) | dirs
	$(CC) $(OBJS) $(LDFLAGS) $(LDLIBS) -o $@
	@echo "Built $@"

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c | dirs
	$(CC) $(CFLAGS) -c $< -o $@

$(OBJ_DIR)/common_%.o: $(ROOT)/common/src/%.c | dirs
	$(CC) $(CFLAGS) -c $< -o $@

dirs:
	@mkdir -p $(OBJ_DIR) $(BIN_DIR)

run: all
	@$(RUN_ENV) ./$(TARGET) $(ARGS)

clean:
	@rm -rf $(OBJ_DIR) $(BIN_DIR)
	@echo "Cleaned $(EXAMPLE)"
